# Use the node:23-alpine3.20 image as the base image
FROM node:23-alpine3.20

# Set the working directory to /app
WORKDIR /app

# Copy all files from the current directory to the /app directory in the container
COPY . .

# Set the command to run when the container starts
CMD node hello.js
